GET http://localhost:8080/users HTTP/1.1

# GET http://localhost:8080/users/2 HTTP/1.1

# POST http://localhost:8080/users HTTP/1.1
# content-type: application/json

# {
#     "name": "Daniel"
# }

# PUT http://localhost:8080/users/2 HTTP/1.1
# content-type: application/json

# {
#     "name": "Sara"
# }

# DELETE http://localhost:8080/users/2 HTTP/1.1